import Head from "next/head";
import styles from "../styles/Home.module.css";
import fsPromises from "fs/promises";
import path from "path";

export default function Home(props) {
  const foods = props.foods;
  debugger;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {foods.map((food) => (
          <li>{food.name}</li>
        ))}
      </ul>
    </div>
  );
}

// load from local data file.

export async function getStaticProps() {
  // TODO - determine why a popup was displayed in Chrome on Mac to allow for local file access. Is this just in develop environment?
  const filePath = path.join(process.cwd(), "data.json");
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData);
  console.log(objectData);
  return {
    props: objectData,
  };
}
